# Generated by Django 4.2.28 on 2026-02-07 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PutevoyForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('oid', models.IntegerField(blank=True, db_index=True, null=True)),
                ('dt_from', models.DateTimeField(blank=True, null=True)),
                ('dt_to', models.DateTimeField(blank=True, null=True)),
                ('km_spread', models.FloatField(default=0)),
                ('tons_sum', models.FloatField(default=0)),
                ('km_gps', models.FloatField(default=0)),
                ('delivery', models.FloatField(default=0)),
                ('idle', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PutevoyFormRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_no', models.IntegerField()),
                ('route', models.CharField(blank=True, max_length=255)),
                ('km', models.FloatField(default=0)),
                ('tons', models.FloatField(default=0)),
                ('width', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('pss_tonnage', models.FloatField(blank=True, null=True)),
                ('delivery', models.FloatField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='formsapp.putevoyform')),
            ],
        ),
    ]
