# Generated by Django 4.2.28 on 2026-02-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='putevoyform',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='putevoyform',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='putevoyform',
            name='idle',
        ),
        migrations.RemoveField(
            model_name='putevoyform',
            name='km_gps',
        ),
        migrations.RemoveField(
            model_name='putevoyform',
            name='km_spread',
        ),
        migrations.RemoveField(
            model_name='putevoyform',
            name='tons_sum',
        ),
        migrations.AddField(
            model_name='putevoyform',
            name='mongo_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='putevoyform',
            name='payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='putevoyform',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='putevoyform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterModelTable(
            name='putevoyform',
            table='putevoy_forms',
        ),
    ]
