# Generated by Django 4.2.28 on 2026-02-07 10:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('road_width_m', models.FloatField(blank=True, null=True)),
                ('road_length_km', models.FloatField(blank=True, null=True)),
                ('pss_tonnage_t', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.IntegerField(db_index=True)),
                ('tm', models.DateTimeField(db_index=True)),
                ('idx', models.IntegerField(blank=True, db_index=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
            ],
            options={
                'indexes': [models.Index(fields=['oid', 'idx'], name='tracking_tr_oid_f11f5e_idx'), models.Index(fields=['oid', 'tm'], name='tracking_tr_oid_b41971_idx')],
            },
        ),
    ]
