# Generated by Django 4.2.28 on 2026-02-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackpoint',
            name='odo_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackpoint',
            name='speed_kmh',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
